"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUpRight, ChevronDown, FileText, Maximize2 } from "lucide-react";
import { type CaseStudy, type StudyRender, type StudyTest, renderCount, setupLabel } from "@/data/case-studies/types";
import { CaseStudyTest } from "./CaseStudyTest";
import { ComparisonViewer, type ViewerState } from "./ComparisonViewer";
import { StudyImage } from "./StudyImage";
import { FutureStudies, StudyFooter, StudyStats } from "./StudyPrimitives";
import s from "./CaseStudies.module.css";

export function ExperimentMatrix({ study, onInspect }: { study: CaseStudy; onInspect: (test: StudyTest, render: StudyRender) => void }) {
  return <section id="matrix" className={s.matrixSection} aria-labelledby="matrix-title"><div className={s.sectionHeading}><span className={s.eyebrow}>EXPERIMENT MATRIX</span><h2 id="matrix-title">Të gjitha, në një pamje.</h2><p>{study.tests.length} brief-e. {renderCount(study)} interpretime. Çdo imazh hapet në madhësi të plotë.</p></div><div className={s.matrixScroll} tabIndex={0} role="region" aria-label="Matrica e plotë e eksperimentit; rrëshqit horizontalisht"><table className={s.matrix}><caption className={s.srOnly}>{study.title}: të gjitha gjenerimet sipas testit dhe konfigurimit</caption><thead><tr><th scope="col">TEST / SETUP</th>{study.setups.map((setup) => <th scope="col" key={setup.id}><span className={setup.isMaro ? s.maroLabel : undefined}>{setup.provider}</span><small>{setup.brain ? `maroBrain ${setup.brain}` : setup.model}</small></th>)}</tr></thead><tbody>{study.tests.map((test) => <tr key={test.id}><th scope="row"><small>TEST {test.number}</small>{test.title}</th>{study.setups.map((setup) => { const render = test.renders.find((item) => item.setupId === setup.id); return <td key={setup.id}>{render ? <button type="button" onClick={() => onInspect(test, render)} aria-label={`Zmadho ${test.title} — ${setupLabel(setup)}`}><StudyImage asset={render} sizes="180px" /></button> : <span>Pa rezultat</span>}</td>; })}</tr>)}</tbody></table></div></section>;
}

export function StudyEvidence({ study }: { study: CaseStudy }) {
  return <details className={s.evidence} id="evidence"><summary><span><FileText size={20} aria-hidden />Metodologjia & Evidenca</span><ChevronDown size={20} aria-hidden /></summary><div className={s.evidenceBody}><div><h3>Protokolli i eksperimentit</h3><p>{study.methodology.statement}</p><p>{study.methodology.provenance}</p><p>{study.methodology.limitations}</p><ul>{study.setups.map((setup) => <li key={setup.id}>{setupLabel(setup)}</li>)}</ul>{study.date && <p>Data: <time dateTime={study.date}>{study.date}</time></p>}</div><div><h3>Materiali burimor</h3>{study.evidence.map((item) => <a className={s.evidenceLink} key={item.src} href={item.src} target="_blank" rel="noreferrer"><FileText size={20} /><span>{item.title}<small>{item.type.toUpperCase()} · Hap në skedë të re</small></span><ArrowUpRight size={18} /></a>)}<p>Promptet origjinale, pa shkurtim:</p>{study.tests.map((test) => <details className={s.evidencePrompt} key={test.id}><summary>Test {test.number} · {test.title}</summary><pre>{test.prompt}</pre></details>)}</div></div></details>;
}

export function CaseStudyDetail({ study }: { study: CaseStudy }) {
  const [viewer, setViewer] = useState<ViewerState | null>(null);
  const inspect = (test: StudyTest, render: StudyRender) => setViewer({ kind: "image", asset: render, title: `Test ${test.number} · ${setupLabel(study.setups.find((setup) => setup.id === render.setupId)!)}` });
  return <div className={s.page}>
    <Link href="/case-studies" className={s.back}><ArrowLeft size={15} aria-hidden /> Case Studies</Link>
    <header className={s.caseHeader}>
      <div className={s.caseHeaderCopy}><div className={s.headerTags}><span className={s.eyebrow}>CASE STUDY {study.number}</span><span className={s.module}>{study.module}</span><span>{study.category}</span></div><h1>{study.title}</h1><h2>{study.headline.map((line) => <span key={line}>{line}</span>)}</h2><p>{study.introduction}</p><a href={`#${study.tests[0].id}`} className={s.textLink}>Shiko eksperimentet <ArrowDown size={16} /></a></div>
      <button className={s.specimenHero} type="button" onClick={() => setViewer({ kind: "image", asset: study.inputs[0], title: `INPUT 01 · ${study.inputs[0].label ?? study.brand}` })} aria-label="Zmadho attachment-in origjinal"><StudyImage asset={study.inputs[0]} sizes="(max-width: 699px) 50vw, 320px" priority /><span>INPUT 01 <Maximize2 size={14} aria-hidden /></span></button>
    </header>
    <StudyStats items={[{ value: study.tests.length, label: "prompts" }, { value: study.inputs.length, label: "attachment" }, { value: study.setups.length, label: "setups" }, { value: renderCount(study), label: "renders" }]} />
    <section className={s.protocol} aria-labelledby="protocol-title"><div className={s.sectionHeading}><span className={s.eyebrow}>01 / PROTOKOLLI</span><h2 id="protocol-title">I njëjti fillim.<br />Katër drejtime.</h2></div><div><div className={s.equation}><div><small>SAME</small><strong>Prompt<br />Product<br />Brief</strong></div><ArrowRight aria-hidden /><div><small>CHANGES</small><strong>System<br />Brand context</strong></div><ArrowRight aria-hidden /><div><small>OUTPUTS</small><strong className={s.outputCount}>{renderCount(study)}</strong></div></div><p className={s.protocolCopy}>{study.methodology.statement}</p><a href="#evidence" onClick={() => { const evidence = document.getElementById("evidence"); if (evidence instanceof HTMLDetailsElement) evidence.open = true; }} className={s.textLink}>Shiko metodologjinë <ArrowUpRight size={14} /></a></div></section>
    <section className={s.inputSection} aria-labelledby="input-title"><button type="button" onClick={() => setViewer({ kind: "image", asset: study.inputs[0], title: `INPUT 01 · ${study.inputs[0].label ?? study.brand}` })} aria-label={`Inspekto referencën ${study.inputs[0].label ?? study.brand}`}><StudyImage asset={study.inputs[0]} sizes="150px" /><Maximize2 size={16} aria-hidden /></button><div><span className={s.eyebrow}>INPUT 01 / SHARED REFERENCE</span><h2 id="input-title">{study.inputs[0].label ?? study.brand}</h2><p>I njëjti attachment në çdo gjenerim.</p><span className={s.inputMeta}>{study.inputs[0].width} × {study.inputs[0].height} · PNG · Origjinali</span></div><span className={s.inputIndex}>01</span></section>
    <nav className={s.testNav} aria-label="Navigimi i eksperimentit"><span className={s.eyebrow}>EKSPERIMENTET</span><div>{study.tests.map((test) => <a key={test.id} href={`#${test.id}`}><span>{test.number}</span>{test.title}</a>)}<a href="#matrix">Matrica <ArrowDown size={13} /></a></div></nav>
    {study.tests.map((test) => <CaseStudyTest key={test.id} test={test} study={study} onInspect={(render) => inspect(test, render)} onCompare={(pair) => setViewer({ kind: "compare", test, pair })} />)}
    <section className={s.brainSection} aria-labelledby="brain-title"><div className={s.sectionHeading}><span className={s.eyebrow}>KONTEKSTI / maroBrain</span><h2 id="brain-title">Prompti ishte i njëjtë.<br /><span>Konteksti jo.</span></h2></div><div className={s.brainTransition}><div><span className={s.brainState}>maroBrain <b>OFF</b></span><p>Modeli sheh kërkesën dhe attachment-in.</p></div><ArrowRight size={26} aria-hidden /><div><span className={s.brainState}>maroBrain <b>ON</b></span><p>Maro mund të përdorë kontekstin e brandit, targetin, qëllimet, tregun dhe drejtimin e komunikimit të ruajtur në maroBrain.</p></div></div><p className={s.contextLabel}>{study.brand} / PËRMBLEDHJA E KONTEKSTIT TË DHËNË NGA AUTORI</p><div className={s.contextGrid}>{study.maroBrain.map((item) => <div key={item.label}><span className={s.eyebrow}>{item.label}</span><h3>{item.title}</h3><p>{item.description}</p></div>)}</div></section>
    <ExperimentMatrix study={study} onInspect={inspect} /><StudyEvidence study={study} />
    <section className={s.conclusion} aria-labelledby="conclusion-title"><span className={s.eyebrow}>PA PIKËZIM. PA FITUES TË PARACAKTUAR.</span><h2 id="conclusion-title">Dallimin vendose ti.</h2><p>Case Studies të Maro-s përdorin brief-e dhe inpute të kontrolluara për ta bërë krahasimin sa më të qartë. Eksperimentet e ardhshme do të testojnë kategori, modele dhe module të tjera.</p><div><Link className={s.primaryButton} href={study.cta.href}>{study.cta.label}<ArrowUpRight size={18} /></Link><Link className={s.button} href="/case-studies">Shiko Case Studies <ArrowRight size={18} /></Link></div></section>
    <FutureStudies /><StudyFooter />
    {viewer && <ComparisonViewer key={viewer.kind === "compare" ? `${viewer.test.id}-compare` : viewer.asset.src} state={viewer} study={study} onClose={() => setViewer(null)} />}
  </div>;
}
