// Real independent PostgreSQL sessions. This harness refuses non-loopback destinations.
import { spawn } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const executable = path.resolve('scripts/phase5-data/postgresql-runtime/pgsql/bin/psql.exe');
const database = 'phase5_test';
const q = (v) => `'${String(v).replaceAll("'", "''")}'`;
function sql(statement) {
  return new Promise((resolve,reject) => {
    const child=spawn(executable,['-X','-h','127.0.0.1','-p','55435','-U','phase5','-d',database,'-v','ON_ERROR_STOP=1','-Atq'],{windowsHide:true});
    let out='',err=''; child.stdout.on('data',b=>out+=b);child.stderr.on('data',b=>err+=b);
    child.on('error',reject);child.on('close',code=>code===0?resolve(out.trim()):reject(Error(err.trim())));child.stdin.end(statement);
  });
}
const checks=[];
async function test(name,work){await work();checks.push(name);console.log('PASS',name);}
async function user(credits=10){const id=randomUUID();await sql(`insert into auth.users values(${q(id)});insert into profiles(id,email,credits) values(${q(id)},'phase5@test.invalid',${credits});insert into workspaces(id,owner_id) values(${q(`ws_${id}`)},${q(id)});`);return id;}
async function job(uid,key=randomUUID()){
  const id=randomUUID();const snapshot={userId:uid,registryToolId:'reklama',module:'maro_imazh',prompt:'Internal lifecycle test',logicalModel:'flare',model:{provider:'openai',providerModelId:'gpt-image-2.5-flare',customerCredits:5},imageCount:1,selections:{},workspaceId:`ws_${uid}`};
  const metadata={v1_durable:true,v1_request:snapshot,canonical_prompt:{hash:'test-hash'}};
  await sql(`insert into generation_jobs(id,user_id,module,model,idempotency_key,metadata) values(${q(id)},${q(uid)},'reklama','gpt-image-2.5-flare',${q(key)},${q(JSON.stringify(metadata))});insert into pricing_snapshots(job_id,snapshot) values(${q(id)},'{"record_type":"v1_image_execution","canonical":{"provenance":{"promptHash":"test-hash"}}}');`);return id;
}
const reserve=(uid,id)=>sql(`select reserve_credits(${q(uid)},5,${q(id)},'test');`);
const finalize=id=>sql(`select settle_v1_image_job(${q(id)});`);
const release=id=>sql(`select release_credit_reserve(${q(id)},'test-release');`);
async function stored(uid,id){assert.equal(await sql(`select start_v1_image_job(${q(id)});`),'t');assert.equal(await sql(`select mark_v1_image_provider_result(${q(id)},repeat('a',64));`),'t');await sql(`insert into storage.objects(bucket_id,name,metadata) values('generations',${q(`${uid}/${id}/output.png`)},'{"size":500}');`);}
const persist=id=>sql(`select persist_v1_image_generation(${q(id)});`);
const state=id=>sql(`select json_build_object('status',j.status,'charged',j.credits_charged,'reserved',j.credits_reserved,'history',(select count(*) from generations where job_id=j.id),'charges',(select count(*) from credit_transactions where job_id=j.id and type='charge'),'releases',(select count(*) from credit_transactions where job_id=j.id and type='release')) from generation_jobs j where id=${q(id)};`).then(JSON.parse);
const balance=uid=>sql(`select json_build_array(credits,credits_reserved) from profiles where id=${q(uid)};`).then(JSON.parse);
await test('text workspace IDs retain the correct owned workspace in history',async()=>{const u=await user();const j=await job(u);await reserve(u,j);await stored(u,j);await persist(j);assert.equal(await sql(`select workspace_id from generations where job_id=${q(j)};`),`ws_${u}`);assert.equal(await finalize(j),'finalized');});
await test('10 credits supports two concurrent 5-credit reservations; no double subtraction',async()=>{const u=await user();const a=await job(u),b=await job(u);const values=await Promise.all([reserve(u,a),reserve(u,b)]);assert.deepEqual(values.sort(),['0','5']);assert.deepEqual(await balance(u),[0,10]);await Promise.all([release(a),release(b)]);assert.deepEqual(await balance(u),[10,0]);});
await test('concurrent reserve on one job debits once',async()=>{const u=await user();const j=await job(u);await Promise.all(Array.from({length:8},()=>reserve(u,j)));assert.deepEqual(await balance(u),[5,5]);assert.equal(await sql(`select count(*) from credit_transactions where job_id=${q(j)} and type='reserve';`),'1');await release(j);});
await test('provider/storage failure cannot finalize and releases once',async()=>{const u=await user();const j=await job(u);await reserve(u,j);assert.equal(await finalize(j),'evidence_missing');await Promise.all(Array.from({length:8},()=>release(j)));assert.deepEqual(await state(j),{status:'failed',charged:0,reserved:0,history:0,charges:0,releases:1});assert.deepEqual(await balance(u),[10,0]);assert.equal(await finalize(j),'invalid_state');});
await test('history insert rollback keeps durable object and prevents charge',async()=>{const u=await user();const j=await job(u);await reserve(u,j);await stored(u,j);await sql(`create function reject_phase5_history() returns trigger language plpgsql as $$ begin raise exception 'injected_history_failure'; end $$;create trigger reject_phase5_history before insert on generations for each row execute function reject_phase5_history();`);await assert.rejects(persist(j),/injected_history_failure/);await sql('drop trigger reject_phase5_history on generations;drop function reject_phase5_history();');assert.equal(await finalize(j),'evidence_missing');assert.equal(await sql(`select fail_v1_image_job(${q(j)},'history_failed');`),'released');assert.equal((await state(j)).history,0);assert.equal(await sql(`select count(*) from storage.objects where name=${q(`${u}/${j}/output.png`)};`),'1');});
await test('duplicate history and 12 simultaneous finalizations produce one history and one charge',async()=>{const u=await user();const j=await job(u);await reserve(u,j);await stored(u,j);const ids=await Promise.all(Array.from({length:6},()=>persist(j)));assert.equal(new Set(ids).size,1);const results=await Promise.all(Array.from({length:12},()=>finalize(j)));assert.equal(results.filter(x=>x==='finalized').length,1);assert.equal(results.filter(x=>x==='already_finalized').length,11);assert.deepEqual(await state(j),{status:'completed',charged:5,reserved:0,history:1,charges:1,releases:0});assert.equal(await release(j),'f');assert.deepEqual(await balance(u),[5,0]);});
await test('settlement exception rolls back charge and retains history for later completion',async()=>{const u=await user();const j=await job(u);await reserve(u,j);await stored(u,j);await persist(j);await sql(`create function reject_phase5_charge() returns trigger language plpgsql as $$ begin if new.type='charge' then raise exception 'injected_charge_failure'; end if;return new; end $$;create trigger reject_phase5_charge before insert on credit_transactions for each row execute function reject_phase5_charge();`);await assert.rejects(finalize(j),/injected_charge_failure/);await sql('drop trigger reject_phase5_charge on credit_transactions;drop function reject_phase5_charge();');assert.deepEqual(await state(j),{status:'processing',charged:0,reserved:5,history:1,charges:0,releases:0});assert.equal(await release(j),'f');assert.equal(await finalize(j),'finalized');assert.equal(await finalize(j),'already_finalized');});
await test('release/finalize race on a persisted result cannot refund it',async()=>{for(let i=0;i<8;i++){const u=await user();const j=await job(u);await reserve(u,j);await stored(u,j);await persist(j);await Promise.all([release(j),finalize(j),release(j),finalize(j)]);assert.deepEqual(await state(j),{status:'completed',charged:5,reserved:0,history:1,charges:1,releases:0});}});
await test('release versus late history insertion has one coherent outcome',async()=>{for(let i=0;i<8;i++){const u=await user();const j=await job(u);await reserve(u,j);await stored(u,j);await Promise.allSettled([release(j),persist(j)]);const s=await state(j);if(s.status==='failed'){assert.equal(s.history,0);assert.equal(await finalize(j),'invalid_state');}else{assert.equal(s.history,1);assert.equal(await finalize(j),'finalized');}const terminal=await state(j);assert.equal(terminal.charges+terminal.releases,1);}});
await test('stale recovery after storage creates history and finalizes once amid concurrent finalize/reconcile',async()=>{const u=await user();const j=await job(u);await reserve(u,j);await stored(u,j);await sql(`update generation_jobs set created_at=now()-interval '30 minutes' where id=${q(j)};`);await Promise.all([sql(`select reconcile_generation_job(${q(j)},15);`),sql(`select reconcile_generation_job(${q(j)},15);`),finalize(j)]);assert.deepEqual(await state(j),{status:'completed',charged:5,reserved:0,history:1,charges:1,releases:0});});
await test('stale provider result without storage releases; late output cannot resurrect job',async()=>{const u=await user();const j=await job(u);await reserve(u,j);await sql(`select mark_v1_image_provider_result(${q(j)},repeat('b',64));update generation_jobs set created_at=now()-interval '30 minutes' where id=${q(j)};select reconcile_generation_job(${q(j)},15);`);assert.equal((await state(j)).releases,1);await assert.rejects(sql(`update generation_jobs set status='processing' where id=${q(j)};`),/terminal_generation_job/);await assert.rejects(persist(j),/invalid_persistence_state/);});
await test('duplicate submissions cannot create two jobs, including after completion',async()=>{const u=await user();const key=randomUUID();const result=await Promise.allSettled([job(u,key),job(u,key),job(u,key)]);assert.equal(result.filter(r=>r.status==='fulfilled').length,1);const j=result.find(r=>r.status==='fulfilled').value;await reserve(u,j);await stored(u,j);await persist(j);await finalize(j);await assert.rejects(job(u,key),/generation_idempotency_conflict/);});
await test('terminal failure permits retry with the same key on a new separately reserved job',async()=>{const u=await user();const key=randomUUID();const old=await job(u,key);await reserve(u,old);await release(old);const retry=await job(u,key);assert.notEqual(old,retry);assert.equal(await reserve(u,retry),'5');assert.deepEqual(await balance(u),[5,5]);await release(retry);});
await test('missing/wrong storage, trace, model or history ownership prevents a charge',async()=>{for(const mode of ['storage','trace','model','owner']){const u=await user();const j=await job(u);await reserve(u,j);await stored(u,j);await persist(j);if(mode==='storage')await sql(`delete from storage.objects where name=${q(`${u}/${j}/output.png`)};`);if(mode==='trace')await sql(`delete from pricing_snapshots where job_id=${q(j)};`);if(mode==='model')await sql(`update generations set model='wrong' where job_id=${q(j)};`);if(mode==='owner')await sql(`update generations set user_id=${q(await user())} where job_id=${q(j)};`);assert.equal(await finalize(j),'evidence_missing');assert.equal((await state(j)).charges,0);assert.equal(await release(j),'f');}});
await test('new privileged RPCs deny ordinary roles',async()=>{for(const signature of ['settle_v1_image_job(uuid)','persist_v1_image_generation(uuid)','fail_v1_image_job(uuid,text)','reconcile_generation_job(uuid,integer)','mark_v1_image_provider_result(uuid,text,jsonb)'])assert.equal(await sql(`select has_function_privilege('authenticated',${q(signature)},'execute');`),'f');});
const report={database:'isolated PostgreSQL 17, loopback only',passed:checks.length,checks,providerCalls:0,customerDataUsed:false};fs.writeFileSync('scripts/phase5-data/database-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
