import "server-only";

export const MARO_IMAGE_RESULT_RESOURCE_URI = "ui://maro/image-result-v1.html";
export const MCP_APP_HTML_MIME_TYPE = "text/html;profile=mcp-app";

const FALLBACK_STORAGE_ORIGIN = "https://pbhzobqpavkuttdipjaq.supabase.co";

function storageOrigin(): string {
  const configured = process.env.NEXT_PUBLIC_SUPABASE_URL?.trim();
  if (!configured) return FALLBACK_STORAGE_ORIGIN;

  try {
    const url = new URL(configured);
    return url.protocol === "https:" ? url.origin : FALLBACK_STORAGE_ORIGIN;
  } catch {
    return FALLBACK_STORAGE_ORIGIN;
  }
}

export function getMaroImageResultResourceMeta() {
  const resourceDomains = [storageOrigin()];
  return {
    ui: {
      prefersBorder: true,
      csp: {
        connectDomains: [],
        resourceDomains,
      },
    },
    "openai/widgetDescription":
      "Displays the single image created by Maro for the connected user's active workspace.",
    "openai/widgetPrefersBorder": true,
    "openai/widgetCSP": {
      connect_domains: [],
      resource_domains: resourceDomains,
    },
  };
}

export const MARO_IMAGE_RESULT_HTML = String.raw`<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <meta name="referrer" content="no-referrer" />
    <style>
      :root { color-scheme: light dark; font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
      * { box-sizing: border-box; }
      body { margin: 0; background: transparent; }
      .card { width: 100%; overflow: hidden; border-radius: 16px; background: rgba(127, 127, 127, 0.08); }
      .frame { display: grid; min-height: 160px; place-items: center; }
      img { display: block; width: 100%; height: auto; max-height: 760px; object-fit: contain; }
      .status { padding: 24px 16px; color: rgba(127, 127, 127, 0.95); text-align: center; font-size: 14px; }
      .meta { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 10px 12px; font-size: 12px; }
      .brand { font-weight: 700; letter-spacing: 0.02em; }
      .credits { color: rgba(127, 127, 127, 0.95); }
      [hidden] { display: none !important; }
      @media (max-width: 520px) {
        .card { border-radius: 12px; }
        .meta { padding: 9px 10px; }
      }
    </style>
  </head>
  <body>
    <main class="card" aria-live="polite">
      <div class="frame">
        <p id="status" class="status">Loading the Maro image…</p>
        <img id="image" alt="Image generated by Maro" referrerpolicy="no-referrer" hidden />
      </div>
      <div id="meta" class="meta" hidden>
        <span class="brand">Maro</span>
        <span id="credits" class="credits"></span>
      </div>
    </main>
    <script>
      (function () {
        var image = document.getElementById("image");
        var status = document.getElementById("status");
        var meta = document.getElementById("meta");
        var credits = document.getElementById("credits");

        function structuredContent(value) {
          if (!value || typeof value !== "object") return null;
          if (value.structuredContent && typeof value.structuredContent === "object") {
            return value.structuredContent;
          }
          return value;
        }

        function safeHttpsUrl(value) {
          if (typeof value !== "string") return null;
          try {
            var parsed = new URL(value);
            return parsed.protocol === "https:" ? parsed.href : null;
          } catch (_) {
            return null;
          }
        }

        function render(value) {
          var output = structuredContent(value);
          var assetUrl = safeHttpsUrl(output && output.asset_url);
          if (!assetUrl) return false;

          image.src = assetUrl;
          image.hidden = false;
          status.hidden = true;
          meta.hidden = false;
          credits.textContent = typeof output.credits_spent === "number"
            ? String(output.credits_spent) + " credits used"
            : "Generated image";
          return true;
        }

        window.addEventListener("message", function (event) {
          if (event.source !== window.parent) return;
          var message = event.data;
          if (!message || message.jsonrpc !== "2.0") return;
          if (message.method === "ui/notifications/tool-result") {
            render(message.params);
          }
        }, { passive: true });

        image.addEventListener("load", function () {
          if (window.openai && typeof window.openai.notifyIntrinsicHeight === "function") {
            window.openai.notifyIntrinsicHeight();
          }
        });
        image.addEventListener("error", function () {
          image.hidden = true;
          status.hidden = false;
          status.textContent = "The generated image could not be loaded.";
        });
      })();
    </script>
  </body>
</html>`;
