import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import assert from 'node:assert/strict';
import { build } from '../../node_modules/.pnpm/esbuild@0.28.2/node_modules/esbuild/lib/main.js';
import puppeteer from 'puppeteer-core';
const output=path.resolve('scripts/phase6-data');
await build({entryPoints:['tools/phase6/browser-entry.jsx'],bundle:true,outfile:path.join(output,'browser.js'),platform:'browser',jsx:'automatic',alias:{'@':path.resolve('src')},plugins:[{name:'fixture-auth-headers',setup(b){b.onResolve({filter:/^@\/lib\/admin\/clientFetch$/},()=>({path:'fixture-auth',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:'export async function adminAuthHeaders(){return {}}',loader:'js'}));}}]});
const tokens=['maro-final-design-system/tokens/maro-final.css','maro-final-design-system/components/maro-final-primitives.css','maro-final-design-system/components/maro-final-layouts.css','src/styles/maro-compat.css','src/components/marologo/marologo.css'].map(p=>fs.readFileSync(p,'utf8')).join('\n');
fs.writeFileSync(path.join(output,'browser.html'),`<!doctype html><html><meta charset="utf-8"><link rel="stylesheet" href="browser.css"><style>${tokens}body{font-family:Manrope,Arial,sans-serif;background:var(--canvas);color:var(--ink)}</style><body><div id="root"></div><script src="browser.js"></script></body></html>`);
const browser=await puppeteer.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--disable-background-networking','--disable-extensions','--no-first-run']});
const checks=[];try {
 const page=await browser.newPage();page.setDefaultTimeout(10000);await page.setViewport({width:1440,height:1100});await page.setRequestInterception(true);page.on('request',r=>r.url().startsWith('file:')?r.continue():r.abort());
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto(pathToFileURL(path.join(output,'browser.html')).href);await page.waitForSelector('fieldset input');
 const click=async text=>{await page.waitForFunction(text=>[...document.querySelectorAll("button")].some(b=>b.textContent.trim()===text&&!b.disabled),{},text);const found=await page.evaluate(text=>{const b=[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===text);if(!b) return false;b.click();return true;},text);assert.ok(found,`button ${text}`);};
 const fill=async(label,value)=>{const selector=await page.evaluate(label=>{const l=[...document.querySelectorAll('label')].find(l=>l.querySelector('span')?.textContent===label);const el=l?.querySelector('input,textarea');if(!el)return null;el.setAttribute('data-test-field','active');return '[data-test-field="active"]';},label);assert.ok(selector,label);await page.click(selector);await page.keyboard.down('Control');await page.keyboard.press('KeyA');await page.keyboard.up('Control');await page.keyboard.type(value);await page.evaluate(()=>document.querySelector('[data-test-field]')?.removeAttribute('data-test-field'));};
 await fill('Customer credits','6');await click('Save production models');await page.waitForFunction(()=>window.phase6Fixture.models[0].customerCredits===6);checks.push('price editing submits the production model set');
 await click('Create draft from published');await page.waitForFunction(()=>document.querySelector('textarea[aria-label="System prompt"]')?.readOnly===false);await page.click('textarea[aria-label="System prompt"]');await page.keyboard.down('Control');await page.keyboard.press('KeyA');await page.keyboard.up('Control');await page.keyboard.type('Edited synthetic draft');await click('Save draft');await page.waitForFunction(()=>window.phase6Fixture.versions[0].content==='Edited synthetic draft');assert.equal(await page.evaluate(()=>window.phase6Fixture.versions.find(v=>v.status==='live').content),'Synthetic production prompt for UI verification.');await click('Preview saved version');await page.waitForFunction(()=>document.querySelector('pre')?.textContent.includes('DRAFT PREVIEW'));await click('Publish saved draft');await page.waitForFunction(()=>window.phase6Fixture.versions.find(v=>v.status==='live').content==='Edited synthetic draft');checks.push('draft save, preview, explicit publication controls work');
 await page.screenshot({path:path.join(output,'admin-imazh.png'),fullPage:true});
 await click('logo');await page.waitForFunction(()=>document.body.textContent.includes('Save Wizard content'));await fill('Question label','Your brand name');await click('Save Wizard content');await page.waitForFunction(()=>window.phase6Fixture.content['brand.name'].label==='Your brand name');await page.screenshot({path:path.join(output,'admin-logo.png'),fullPage:true});await click('wizard');await page.waitForFunction(()=>document.body.textContent.includes('Your brand name'));await page.screenshot({path:path.join(output,'wizard.png'),fullPage:true});checks.push('saved Logo wording renders in the existing Wizard');
 await click('operations');await page.waitForFunction(()=>document.body.textContent.includes('Retained output without history'));await page.screenshot({path:path.join(output,'operations.png'),fullPage:true});checks.push('completed and released persistence failure render safely');
 assert.deepEqual(errors,[]);checks.push('no browser runtime errors');
 fs.writeFileSync(path.join(output,'browser-results.json'),JSON.stringify({passed:checks.length,checks,scope:'isolated UI fixture, all network blocked; no live admin/MFA claim',providerCalls:0},null,2));console.log(JSON.stringify({passed:checks.length,checks}));
}finally{await browser.close();}
