// Disposable loopback database only. No Supabase/provider calls.
import { spawn } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const executable = path.resolve('scripts/phase5-data/postgresql-runtime/pgsql/bin/psql.exe');
const q = value => `'${String(value).replaceAll("'", "''")}'`;
const sql = statement => new Promise((resolve,reject) => {
  const child=spawn(executable,['-X','-h','127.0.0.1','-p','55435','-U','phase5','-d','phase6_test','-v','ON_ERROR_STOP=1','-Atq'],{windowsHide:true});
  let out='',err='';child.stdout.on('data',v=>out+=v);child.stderr.on('data',v=>err+=v);child.on('error',reject);child.on('close',code=>code===0?resolve(out.trim()):reject(Error(err.trim())));child.stdin.end(statement);
});
const checks=[];async function test(name,work){await work();checks.push(name);console.log('PASS',name);}
const actor=randomUUID();await sql(`insert into auth.users values(${q(actor)});`);
const defaults=[{key:'flare',label:'Flare',descriptor:'Fast · Recommended',enabled:true,isDefault:true,order:0,customerCredits:5},{key:'sunburst',label:'Sunburst',descriptor:'Alternative · More deliberate',enabled:true,isDefault:false,order:1,customerCredits:5}];
await sql(`insert into tool_model_configs(tool_id,model_id,display_name,provider,is_default,metadata,cost_metadata) values
 ('maro_imazh','flare','Flare','openai',true,'{"providerModelId":"gpt-image-2.5-flare","description":"Fast · Recommended"}','{"customerCredits":5,"pricingStage":"launch"}'),
 ('maro_imazh','sunburst','Sunburst','openai',false,'{"providerModelId":"gpt-image-2.5-sunburst","description":"Alternative · More deliberate"}','{"customerCredits":5,"pricingStage":"launch"}'),
 ('maro_logo','flare','Flare','openai',true,'{"providerModelId":"gpt-image-2.5-flare","description":"Fast · Recommended"}','{"customerCredits":5,"pricingStage":"launch"}');`);
const save=(models,tool='maro_imazh')=>sql(`select admin_save_v1_models(${q(tool)},${q(JSON.stringify(models))});`);
const models=()=>sql(`select jsonb_agg(jsonb_build_object('key',model_id,'default',is_default,'enabled',enabled,'credits',cost_metadata->'customerCredits','description',metadata->>'description') order by model_id) from tool_model_configs where tool_id='maro_imazh';`).then(JSON.parse);
await test('model price and description persist on authoritative rows',async()=>{const changed=structuredClone(defaults);changed[0].customerCredits=6;changed[0].descriptor='Temporary descriptor';await save(changed);assert.equal((await models())[0].credits,6);assert.equal((await models())[0].description,'Temporary descriptor');});
await test('default switch is atomic with exactly one enabled default',async()=>{const changed=structuredClone(defaults);changed[0].isDefault=false;changed[1].isDefault=true;await save(changed);assert.equal((await models()).find(m=>m.default).key,'sunburst');});
await test('competing configuration saves serialize safely',async()=>{const switched=structuredClone(defaults);switched[0].isDefault=false;switched[1].isDefault=true;await Promise.all(Array.from({length:8},(_,i)=>save(i%2?defaults:switched)));assert.equal((await models()).filter(m=>m.default).length,1);});
await test('invalid price/default/Logo edits roll back without damaging prior state',async()=>{const before=await models();for(const kind of ['zero','multiple','none','disabled']){const edit=structuredClone(defaults);if(kind==='zero')edit[0].customerCredits=0;if(kind==='multiple')edit[1].isDefault=true;if(kind==='none')edit[0].isDefault=false;if(kind==='disabled')edit[0].enabled=false;await assert.rejects(save(edit));assert.deepEqual(await models(),before);}await assert.rejects(save(defaults,'maro_logo'));});
await test('disabled Sunburst persists while Flare remains default',async()=>{const changed=structuredClone(defaults);changed[1].enabled=false;await save(changed);assert.equal((await models())[1].enabled,false);await save(defaults);});
const live=randomUUID(),draft=randomUUID(),draft2=randomUUID();
await sql(`insert into system_prompt_versions(id,tool_id,version_label,status,content) values(${q(live)},'maro_imazh','test-live','live','LIVE CONTENT'),(${q(draft)},'maro_imazh','test-draft','draft','DRAFT CONTENT'),(${q(draft2)},'maro_imazh','test-draft2','draft','OTHER DRAFT');`);
const published=()=>sql("select content from system_prompt_versions where tool_id='maro_imazh' and status='live';");
await test('draft save leaves live production untouched',async()=>{await sql(`update system_prompt_versions set content='SAVED DRAFT' where id=${q(draft)};`);assert.equal(await published(),'LIVE CONTENT');});
await test('empty publication is rejected while existing live version remains',async()=>{await sql(`update system_prompt_versions set content=' ' where id=${q(draft)};`);await assert.rejects(sql(`select admin_publish_v1_prompt(${q(draft)},${q(actor)});`),/invalid_prompt_content/);assert.equal(await published(),'LIVE CONTENT');await sql(`update system_prompt_versions set content='SAVED DRAFT' where id=${q(draft)};`);});
await test('publication archives old and publishes selected draft atomically',async()=>{await sql(`select admin_publish_v1_prompt(${q(draft)},${q(actor)});`);assert.equal(await published(),'SAVED DRAFT');assert.equal(await sql(`select status from system_prompt_versions where id=${q(live)};`),'archived');});
await test('failed publication transaction restores the original live version',async()=>{await sql(`create function test_reject_publish() returns trigger language plpgsql as $$ begin if new.status='live' then raise exception 'injected_publish_failure'; end if;return new;end $$;create trigger test_reject_publish before update on system_prompt_versions for each row execute function test_reject_publish();`);await assert.rejects(sql(`select admin_publish_v1_prompt(${q(draft2)},${q(actor)});`),/injected_publish_failure/);await sql('drop trigger test_reject_publish on system_prompt_versions;drop function test_reject_publish();');assert.equal(await published(),'SAVED DRAFT');});
await test('rollback atomically restores an archived version',async()=>{await sql(`select admin_publish_v1_prompt(${q(live)},${q(actor)},true);`);assert.equal(await published(),'LIVE CONTENT');});
const user=randomUUID();await sql(`insert into auth.users values(${q(user)});insert into profiles(id,email,credits) values(${q(user)},'local-phase6@test.invalid',30);`);
async function job(credits=5){const id=randomUUID();const metadata={v1_durable:true,v1_request:{userId:user,registryToolId:'reklama',module:'maro_imazh',prompt:'PRIVATE PROMPT NEVER RETURNED',logicalModel:'flare',model:{provider:'openai',providerModelId:'gpt-image-2.5-flare',customerCredits:credits},imageCount:1,selections:{},workspaceId:null},canonical_prompt:{hash:'test-hash'}};await sql(`insert into generation_jobs(id,user_id,module,model,metadata,created_at) values(${q(id)},${q(user)},'reklama','gpt-image-2.5-flare',${q(JSON.stringify(metadata))},now()-interval '30 minutes');insert into pricing_snapshots(job_id,snapshot) values(${q(id)},'{"record_type":"v1_image_execution","canonical":{"provenance":{"promptHash":"test-hash"}}}');select reserve_credits(${q(user)},${credits},${q(id)},'test');select start_v1_image_job(${q(id)});select mark_v1_image_provider_result(${q(id)},repeat('a',64));insert into storage.objects(bucket_id,name,metadata) values('generations',${q(`${user}/${id}/output.png`)},'{"size":500}');`);return id;}
const operations=()=>sql('select admin_v1_operations();').then(JSON.parse);
await test('operations distinguishes a retained orphan and released history failure without leaking prompts',async()=>{const id=await job();await sql(`select fail_v1_image_job(${q(id)},'history_failed');`);const result=await operations();const j=result.jobs.find(j=>j.id===id);assert.equal(j.module,'maro_imazh');assert.equal(j.model,'flare');assert.equal(j.failure,'history_failed');assert.equal(j.settlement,'released');assert.equal(j.retainedOrphan,true);assert.equal(j.history,'missing');assert.ok(!JSON.stringify(result).includes('PRIVATE PROMPT'));});
await test('operations identifies pending settlement; concurrent reconciliation charges only once',async()=>{const id=await job();await sql(`select persist_v1_image_generation(${q(id)});update generation_jobs set metadata=jsonb_set(metadata,'{v1_lifecycle,phase}','"settlement_pending"'),error='settlement_pending' where id=${q(id)};`);const before=(await operations()).jobs.find(j=>j.id===id);assert.equal(before.phase,'settlement_pending');assert.equal(before.settlement,'reserved');assert.equal(before.eligible,true);await Promise.all(Array.from({length:8},()=>sql(`select reconcile_generation_job(${q(id)},15);`)));const after=(await operations()).jobs.find(j=>j.id===id);assert.equal(after.status,'completed');assert.equal(after.charged,5);assert.equal(after.history,'saved');assert.equal(after.output,'stored');assert.equal(after.settlement,'charged');assert.equal(await sql(`select count(*) from credit_transactions where job_id=${q(id)} and type='charge';`),'1');});
await test('a configured six-credit snapshot is persisted and charged exactly once',async()=>{const changed=structuredClone(defaults);changed[0].customerCredits=6;await save(changed);const price=(await models())[0].credits;const id=await job(price);await sql(`select persist_v1_image_generation(${q(id)});select settle_v1_image_job(${q(id)});select settle_v1_image_job(${q(id)});`);const result=(await operations()).jobs.find(j=>j.id===id);assert.equal(result.configuredCredits,6);assert.equal(result.charged,6);assert.equal(await sql(`select credits_spent from generations where job_id=${q(id)};`),'6');assert.equal(await sql(`select count(*) from credit_transactions where job_id=${q(id)} and type='charge';`),'1');await save(defaults);});
await test('operations filters statuses and never exposes full prompts or Brain',async()=>{const result=JSON.parse(await sql("select admin_v1_operations(null,'failed');"));assert.ok(result.jobs.every(j=>j.status==='failed'));assert.ok(!JSON.stringify(result).includes('v1_request'));});
await test('legacy settings UPDATE permission cannot bypass the protected Logo content API',async()=>{await sql('grant update,select on app_settings to authenticated;');await assert.rejects(sql(`set role authenticated;update app_settings set logo_wizard_content='{}' where id=1;`),/logo_content_requires_admin_api/);await sql('revoke update,select on app_settings from authenticated;');assert.equal(await sql('select logo_wizard_content is null from app_settings where id=1;'),'t');});
await test('all admin functions deny ordinary roles',async()=>{for(const fn of ['admin_publish_v1_prompt(uuid,uuid,boolean)','admin_save_v1_models(text,jsonb)','admin_v1_operations(timestamp with time zone,text)'])for(const role of ['anon','authenticated'])assert.equal(await sql(`select has_function_privilege(${q(role)},${q(fn)},'execute');`),'f');});
await save(defaults);await save([defaults[0]],'maro_logo');
const report={passed:checks.length,checks,database:'disposable phase6_test, PostgreSQL 17 on loopback only',providerCalls:0};fs.writeFileSync('scripts/phase6-data/database-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
