import { PGlite } from "@electric-sql/pglite";
import { readFileSync } from "node:fs";
import { randomUUID } from "node:crypto";
import { describe, expect, it } from "vitest";

const schema = JSON.parse(readFileSync("docs/evidence/schema-baseline-20261009.json", "utf8"));
const quote = (s: string) => '"' + s.replaceAll('"', '""') + '"';
async function database() {
  const db = new PGlite();
  await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
    create schema auth; create schema storage;
    create table auth.users(id uuid primary key);
    create type storage.buckettype as enum ('STANDARD','ANALYTICS','VECTOR');
    create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
    create function auth.role() returns text language sql as $$ select current_setting('request.jwt.claim.role',true) $$;
    create function auth.jwt() returns jsonb language sql as $$ select jsonb_build_object('aal',current_setting('request.jwt.claim.aal',true)) $$;
    grant usage on schema public,auth,storage to anon,authenticated,service_role;`);
  for (const c of schema.columns) {
    const seq = c.default?.match(/nextval\('([^']+)'::regclass\)/)?.[1];
    if (seq) await db.exec(`create sequence if not exists ${seq}`);
  }
  for (const table of [...new Set(schema.columns.map((c: {schema: string; table: string}) => `${c.schema}.${c.table}`))] as string[]) {
    const columns = schema.columns.filter((c: {schema: string; table: string}) => `${c.schema}.${c.table}` === table);
    const defs = columns.map((c: {name: string; type: string; identity: string; generated: string; default: string | null; not_null: boolean}) =>
      `${quote(c.name)} ${c.type}${c.identity ? " generated by default as identity" : c.generated ? ` generated always as (${c.default}) stored` : c.default ? ` default ${c.default}` : ""}${c.not_null ? " not null" : ""}`);
    await db.exec(`create table ${table}(${defs.join(",")})`);
  }
  for (const constraint of [...schema.constraints].sort((a,b) => Number(a.kind === "f") - Number(b.kind === "f"))) {
    await db.exec(`alter table public.${quote(constraint.table)} add constraint ${quote(constraint.name)} ${constraint.definition}`);
  }
  // Existing policy helpers and profile synchronization are exercised unchanged
  // before the staged migration. Infrastructure functions remain Supabase-owned.
  for (const name of ["membership_effective_status", "has_admin_access", "is_admin", "resolve_workspace_limit", "sync_profile_admin_flags", "maro_active_plan", "maro_brain_allowed"]) {
    await db.exec(schema.functions.find((f: {name: string}) => f.name === name).definition);
  }
  for (const table of schema.rls) await db.exec(`alter table ${quote(table.table)} enable row level security`);
  for (const policy of schema.policies.filter((p: {schemaname: string}) => p.schemaname === "public")) {
    await db.exec(`create policy ${quote(policy.policyname)} on ${quote(policy.tablename)} for ${policy.cmd} to ${policy.roles.replace(/[{}]/g, "")}${policy.qual ? ` using (${policy.qual})` : ""}${policy.with_check ? ` with check (${policy.with_check})` : ""}`);
  }
  for (const grant of schema.grants) await db.exec(`grant ${grant.privilege_type} on ${quote(grant.table_name)} to ${grant.grantee}`);
  const trigger = schema.triggers.find((t: {name: string}) => t.name.includes("sync_admin_flags"));
  if (trigger) await db.exec(trigger.definition);
  await db.exec("insert into storage.buckets(id,name) values('generations','generations'),('maro-public','maro-public')");
  for (const migration of ["0057_v1_security_boundaries.sql", "0058_atomic_generation_accounting.sql", "0059_v1_debug_retention.sql"]) await db.exec(readFileSync(`supabase/migrations/${migration}`, "utf8"));
  return db;
}

describe("V1 staged migrations against all 73 catalog-derived public table shapes", () => {
  it("enforces direct-client boundaries, ownership, atomic accounting and paged retention", async () => {
    const db = await database();
    const owner = randomUUID(), other = randomUUID();
    try {
      await db.exec(`insert into auth.users values('${owner}'),('${other}');
        insert into profiles(id,email,full_name) values('${owner}','owner@example.test','Owner'),('${other}','other@example.test','Other');
        insert into app_settings(id,master_prompt) values(1,'PRIVATE');
        set role authenticated; set request.jwt.claim.role='authenticated';
        set request.jwt.claim.sub='${owner}'; set request.jwt.claim.aal='aal1';`);
      await expect(db.query("select master_prompt from app_settings")).rejects.toThrow(/permission denied/);
      await expect(db.query(`update profiles set is_admin=true where id='${owner}'`)).rejects.toThrow(/permission denied/);
      await expect(db.query(`update profiles set access_role='super_admin' where id='${owner}'`)).rejects.toThrow(/permission denied/);
      expect((await db.query(`update profiles set full_name='Renamed' where id='${owner}' returning full_name`)).rows).toEqual([{full_name:"Renamed"}]);
      expect((await db.query(`update profiles set full_name='Hijacked' where id='${other}' returning id`)).rows).toEqual([]);
      await expect(db.query(`select resolve_workspace_limit('${other}')`)).rejects.toThrow(/not_authorized/);
      expect((await db.query(`select resolve_workspace_limit('${owner}') as n`)).rows).toEqual([{n:1}]);
      await db.exec("reset role");
      for (const role of ["editor", "developer", "administrator", "super_admin"]) {
        await db.exec(`update profiles set access_role='${role}' where id='${owner}'; set role authenticated; set request.jwt.claim.aal='aal1'`);
        expect((await db.query("select has_admin_access() as allowed")).rows).toEqual([{allowed:false}]);
        await db.exec("set request.jwt.claim.aal='aal2'");
        expect((await db.query("select has_admin_access() as allowed")).rows).toEqual([{allowed:true}]);
        await expect(db.query(`update profiles set credits=999999 where id='${other}'`)).rejects.toThrow(/permission denied/);
        await expect(db.query("update app_settings set master_prompt='changed'")).rejects.toThrow(/permission denied/);
        await db.exec("reset role");
      }
      const first = randomUUID(), second = randomUUID();
      await db.exec(`insert into generation_jobs(id,user_id,module,status,credits_charged,provider_cost_usd,finished_at) values
        ('${first}','${owner}','reklama','completed',5,0.25,now()),('${second}','${owner}','reklama','completed',7,0.5,now());
        set role service_role; set request.jwt.claim.role='service_role';`);
      await Promise.all([db.query(`select record_job_spend('${first}','${owner}','reklama',0.25,5)`),db.query(`select record_job_spend('${second}','${owner}','reklama',0.5,7)`)]);
      expect((await db.query(`select record_job_spend('${first}','${owner}','reklama',0.25,5) as recorded`)).rows).toEqual([{recorded:false}]);
      const rollup = await db.query("select spend_usd::float,credits_charged,job_count from platform_spend_rollup where bucket_type='day' and module=''");
      expect(rollup.rows).toEqual([{spend_usd:0.75,credits_charged:12,job_count:2}]);
      const record = JSON.stringify({model_id:"test-model",provider:"openai",estimated_cost_usd:0.25,cost_source:"usage_calculated",reconciliation_status:"estimated"});
      await db.query("select record_provider_cost($1,$2::jsonb)",[first,record]);
      await db.query("select record_provider_cost($1,$2::jsonb)",[first,record]);
      expect((await db.query("select count(*)::integer as n from provider_cost_estimates")).rows).toEqual([{n:1}]);
      await db.exec("reset role; insert into provider_cost_estimates(model_id,provider,tool_id,estimated_cost_usd) select 'test','openai','reklama',1 from generate_series(1,5001)");
      await db.exec("set role service_role");
      expect((await db.query("select provider_spend_total('global',null,now()-interval '1 day')::float as spend")).rows).toEqual([{spend:5001.75}]);
      await db.exec(`reset role; insert into data_retention_policies(domain,retention_days) values('generation_debug',90);
        insert into generation_jobs(user_id,module,status,created_at,metadata)
        select '${owner}','reklama','failed',now()-interval '100 days','{"debug":"PRIVATE","v1_request":{"prompt":"PRIVATE","userId":"owner"},"canonical_prompt":{"hash":"retained","text":"PRIVATE"}}'::jsonb from generate_series(1,501);
        set role service_role;`);
      expect((await db.query("select run_v1_debug_retention(500) as n")).rows).toEqual([{n:500}]);
      expect((await db.query("select run_v1_debug_retention(500) as n")).rows).toEqual([{n:1}]);
      expect((await db.query("select run_v1_debug_retention(500) as n")).rows).toEqual([{n:0}]);
      expect((await db.query("select count(*)::integer as n from generation_jobs")).rows).toEqual([{n:503}]);
      expect((await db.query("select metadata from generation_jobs where metadata ? 'debug_purged_at' limit 1")).rows[0]).toMatchObject({metadata:{v1_request:{userId:"owner"},canonical_prompt:{hash:"retained"}}});
      expect((await db.query("select count(*)::integer as n from generation_jobs where metadata->'v1_request' ? 'prompt' or metadata ? 'debug'")).rows).toEqual([{n:0}]);
      await db.exec(`reset role;
        insert into generations(user_id,prompt,final_prompt) values('${owner}','My request','INTERNAL_PROMPT'),('${other}','OTHER_ACCOUNT_PRIVATE','OTHER_INTERNAL');
        insert into credit_transactions(user_id,type,amount,balance_after,metadata) values('${owner}','manual_adjustment',1,1,'{"internal":"PRIVATE"}');`);
      const ticket=randomUUID();
      await db.exec(`insert into support_tickets(id,user_id,subject) values('${ticket}','${owner}','My request');
        insert into support_ticket_messages(ticket_id,body,internal) values('${ticket}','Customer-visible message',false),('${ticket}','PRIVATE_STAFF_NOTE',true);`);
      const exportSql=readFileSync("docs/operations/privacy-export.sql","utf8").replace("REPLACE_WITH_VERIFIED_UUID",owner);
      const results=await db.exec(exportSql);
      const exported=results.flatMap(result=>result.rows).find(row=>"customer_export" in (row as object)) as {customer_export:{creations:unknown[];support_messages:unknown[];credit_history:unknown[]}};
      expect(exported.customer_export.creations).toHaveLength(1);
      expect(exported.customer_export.support_messages).toHaveLength(1);
      expect(exported.customer_export.credit_history).toHaveLength(1);
      const serialized=JSON.stringify(exported);
      for (const privateText of ["INTERNAL_PROMPT","OTHER_ACCOUNT_PRIVATE","OTHER_INTERNAL","PRIVATE_STAFF_NOTE"]) expect(serialized).not.toContain(privateText);
      expect((await db.query("select count(*)::integer as n from credit_transactions")).rows).toEqual([{n:1}]);
    } finally { await db.close(); }
  }, 60000);

  it("serializes V1 admission and counts active or unrecorded completed work against existing limits", async () => {
    const db = await database();
    const owner = randomUUID(), other = randomUUID();
    const admit = (userId = owner, concurrency = 10) => db.query<{ job: { id: string } }>(
      "select create_v1_generation_job($1,'reklama','test',null,0,'{}',0.35,$2) as job", [userId, concurrency]);
    try {
      await db.exec(`insert into auth.users values('${owner}'),('${other}');
        insert into profiles(id,email) values('${owner}','admission@example.test'),('${other}','other@example.test');
        insert into app_settings(id,platform_limits) values(1,'{"hourlySpendUsd":0.7}');
        set role authenticated; set request.jwt.claim.role='authenticated';`);
      await expect(admit()).rejects.toThrow(/permission denied/);
      await db.exec("reset role; set role service_role; set request.jwt.claim.role='service_role'");
      const [a, b] = await Promise.all([admit(), admit()]);
      const first = a.rows[0].job.id, second = b.rows[0].job.id;
      await expect(admit()).rejects.toThrow(/hourly_spend_limit/);
      expect((await db.query("select count(*)::integer as n from generation_jobs")).rows).toEqual([{ n: 2 }]);
      expect((await db.query("select count(*)::integer as n from credit_transactions")).rows).toEqual([{ n: 0 }]);
      expect((await db.query("select provider_spend_total('provider','openai',now()-interval '1 day')::float as spend")).rows).toEqual([{ spend: 0.7 }]);
      await db.query("update generation_jobs set status='completed',finished_at=now(),provider_cost_usd=0.35 where id=$1", [first]);
      await expect(admit()).rejects.toThrow(/hourly_spend_limit/);
      await db.query("select record_job_spend($1,$2,'reklama',0.35,0)", [first, owner]);
      await expect(admit()).rejects.toThrow(/hourly_spend_limit/);
      await db.query("update generation_jobs set status='failed' where id=$1", [second]);
      await admit();
      await expect(admit(owner, 1)).rejects.toThrow(/concurrency_limit/);
      await db.exec("update app_settings set platform_limits='{\"hourlySpendUsd\":100,\"maxActiveJobsGlobal\":1}'");
      await expect(admit(other)).rejects.toThrow(/platform_busy/);
      await db.exec("update generation_jobs set status='failed' where status='pending'; update app_settings set platform_limits='{\"hourlySpendUsd\":100,\"userHourlyUsd\":0.35}'");
      await expect(admit()).rejects.toThrow(/user_hourly_spend_limit/);
      await db.exec("update app_settings set platform_limits='{\"hourlySpendUsd\":100,\"userDailyUsd\":0.35}'");
      await expect(admit()).rejects.toThrow(/user_daily_spend_limit/);
      await db.exec("update app_settings set ai_paused=true");
      await expect(admit()).rejects.toThrow(/ai_paused/);
      await db.exec("update app_settings set ai_paused=false,platform_limits='{\"pausedModules\":[\"reklama\"]}'");
      await expect(admit()).rejects.toThrow(/module_paused/);
    } finally { await db.close(); }
  }, 60000);
});
